(()=>{
const data=[['Последний горизонт','2026','Фантастика','8.4','фильм'],['Ночная линия','2025','Триллер','7.9','фильм'],['Город после дождя','2024','Драма','8.1','фильм'],['Предел','2026','Боевик','8.7','фильм'],['Архив','2025','Детектив','8.6','сериал'],['Северный берег','2023','Приключения','8.0','мультфильм'],['Контур','2025','Фантастика','8.2','аниме'],['Без свидетелей','2024','Криминал','7.8','фильм'],['Параллель','2026','Фантастика','8.5','сериал']];
const pics=['photo-1489599849927-2ee91cede3ba','photo-1536440136628-849c177e76a1','photo-1485846234645-a62644f84728','photo-1517604931442-7e0c8ed2963c','photo-1440404653325-ab127d49abc1','photo-1500534623283-312aade485b7'];
const img=i=>`https://images.unsplash.com/${pics[i%pics.length]}?auto=format&fit=crop&w=1000&q=80`;
const view=document.querySelector('#view'),detail=document.querySelector('#detail'),search=document.querySelector('#search'),results=document.querySelector('#search-results'),input=document.querySelector('#search-input');
const historyKey='oritv-history';let currentZone='content',pos=0,navPos=0;
const getHistory=()=>JSON.parse(localStorage.getItem(historyKey)||'[]');
const saveHistory=i=>{let h=getHistory().filter(x=>x!==i);h.unshift(i);localStorage.setItem(historyKey,JSON.stringify(h.slice(0,30)))};
const card=(x,i)=>`<button class="card focusable" data-id="${i}"><span class="poster" style="background-image:url('${img(i)}')"></span><span class="card-rating">${x[3]}</span><span class="card-info"><span class="card-title">${x[0]}</span><span class="card-sub">${x[1]} · ${x[2]}</span></span></button>`;
const row=(t,a)=>a.length?`<section class="row"><h2 class="row-title">${t}</h2><div class="cards">${a.map(i=>card(data[i],i)).join('')}</div></section>`:'';
function nav(a){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.action===a))}
function bind(){view.querySelectorAll('.focusable').forEach(e=>e.onclick=()=>e.dataset.id!==undefined?open(+e.dataset.id):act(e.dataset.action));focusContent(0)}
function focusContent(n){let a=[...view.querySelectorAll('.focusable')];if(!a.length)return;currentZone='content';pos=Math.max(0,Math.min(n,a.length-1));a.forEach(x=>x.classList.remove('focused'));a[pos].classList.add('focused');a[pos].scrollIntoView({block:'nearest',inline:'nearest'})}
function focusNav(n){let a=[...document.querySelectorAll('.nav-item')];currentZone='nav';navPos=Math.max(0,Math.min(n,a.length-1));a.forEach(x=>x.classList.remove('focused'));a[navPos].classList.add('focused')}
function home(){let h=getHistory();view.innerHTML=`<section class="hero" style="background-image:url('${img(0)}')"><div class="hero-inner"><div class="eyebrow">ORITV · ПРЕМЬЕРА</div><h1>${data[0][0]}</h1><div class="tagline">Когда путь домой становится последней надеждой.</div><div class="meta">${data[0][1]} · ${data[0][2]} · ${data[0][3]}</div><div class="tags"><span class="tag">4K</span><span class="tag">HDR</span><span class="tag">Оригинал</span></div><button class="action primary focusable" data-id="0">▶ Смотреть</button><button class="action focusable" data-id="0">Подробнее</button></div></section><div class="rows">${row('Продолжить просмотр',h.slice(0,6))}${row('Популярное сейчас',[3,4,6,0,7,8])}${row('Новые фильмы',[0,1,2,3,7])}${row('Сериалы',[4,8])}</div>`;nav('home');bind()}
function list(type){let a=data.map((x,i)=>i).filter(i=>type==='all'||data[i][4]===type);view.innerHTML=`<h1 class="page-title">${type==='all'?'Фильмы':type==='history'?'История':type==='favorite'?'Избранное':type==='мультфильм'?'Мультфильмы':type==='аниме'?'Аниме':'Сериалы'}</h1><div class="grid">${a.map(i=>card(data[i],i)).join('')}</div>`;nav(type==='all'?'movies':type==='history'?'history':type==='favorite'?'favorites':type==='мультфильм'?'cartoons':type==='аниме'?'anime':'series');bind()}
function history(){let h=getHistory();let a=h.length?h:[];view.innerHTML=`<h1 class="page-title">История</h1><div class="grid">${a.map(i=>card(data[i],i)).join('')||'<p class="empty">Здесь появятся просмотренные фильмы и серии.</p>'}</div>`;nav('history');bind()}
function settings(){view.innerHTML='<section class="settings"><h1>Настройки</h1><div class="setting-grid"><button class="setting focusable">Источники<br><small>Ваши источники подключаются отдельно.</small></button><button class="setting focusable">Плеер<br><small>Качество, субтитры и запуск.</small></button><button class="setting focusable">Интерфейс<br><small>Синий + оранжевый стиль OriTV.</small></button><button class="setting focusable">Пульт<br><small>Стрелки, OK, Back и Magic Remote.</small></button></div></section>';nav('settings');bind()}
function open(i){let x=data[i];saveHistory(i);detail.querySelector('.detail-backdrop').style.backgroundImage=`url('${img(i)}')`;document.querySelector('#detail-meta').innerHTML=`<div class="detail-info"><div class="eyebrow">${x[4].toUpperCase()} · ${x[1]}</div><h1>${x[0]}</h1><div class="tagline">${x[2]} · рейтинг ${x[3]}</div><div class="tags"><span class="tag">4K</span><span class="tag">HDR</span></div><p class="detail-copy">Здесь будет запуск вашего источника и плеера OriTV.</p><button class="action primary focusable" data-action="close-detail">Назад</button></div>`;detail.classList.remove('hidden');detail.querySelector('[data-action="close-detail"]').onclick=closeDetail}
function closeDetail(){detail.classList.add('hidden');focusContent(pos)}
function act(a){if(a==='home')home();else if(a==='movies')list('all');else if(a==='series')list('сериал');else if(a==='cartoons')list('мультфильм');else if(a==='anime')list('аниме');else if(a==='history')history();else if(a==='favorites')list('favorite');else if(a==='settings')settings();else if(a==='search'){search.classList.remove('hidden');results.innerHTML=data.map((x,i)=>card(x,i)).join('');results.querySelectorAll('.card').forEach(e=>e.onclick=()=>open(+e.dataset.id));input.focus()}}
input.oninput=e=>{let q=e.target.value.toLowerCase();results.innerHTML=data.filter(x=>(x[0]+' '+x[2]).toLowerCase().includes(q)).map((x,i)=>card(x,data.indexOf(x))).join('');results.querySelectorAll('.card').forEach(e=>e.onclick=()=>open(+e.dataset.id))};
document.addEventListener('keydown',e=>{if(!detail.classList.contains('hidden')){if(e.key==='Escape'||e.key==='Backspace')closeDetail();return}if(!search.classList.contains('hidden')){if(e.key==='Escape'||e.key==='Backspace'){search.classList.add('hidden');home()}return}if(currentZone==='nav'){if(e.key==='ArrowLeft')focusNav(navPos-1);else if(e.key==='ArrowRight')focusNav(navPos+1);else if(e.key==='ArrowDown')focusContent(0);else if(e.key==='Enter')document.querySelectorAll('.nav-item')[navPos]?.click();return}if(e.key==='ArrowUp')focusNav(navPos);else if(e.key==='ArrowLeft')focusContent(pos-1);else if(e.key==='ArrowRight')focusContent(pos+1);else if(e.key==='ArrowDown')focusContent(pos+1);else if(e.key==='Enter')view.querySelectorAll('.focusable')[pos]?.click();else if(e.key==='Escape'||e.key==='Backspace')home()});
addEventListener('load',home);
})();