(()=>{
const data=[
 ['Последний горизонт','2026','Фантастика','8.4','фильм'],['Ночная линия','2025','Триллер','7.9','фильм'],['Город после дождя','2024','Драма','8.1','фильм'],['Предел','2026','Боевик','8.7','фильм'],['Архив','2025','Детектив','8.6','сериал'],['Северный берег','2023','Приключения','8.0','мультфильм'],['Контур','2025','Фантастика','8.2','аниме'],['Без свидетелей','2024','Криминал','7.8','фильм'],['Параллель','2026','Фантастика','8.5','сериал'],
 ['Звёздный город','2026','Фантастика','8.6','фильм'],['Тёмная вода','2025','Детектив','8.1','сериал'],['Легенда леса','2024','Приключения','8.3','мультфильм']
];
const posters=[
 'linear-gradient(145deg,#102c55 0%,#1d77bd 42%,#f08a2e 100%)','linear-gradient(145deg,#101828,#344c68 48%,#b04b32)','linear-gradient(145deg,#202b45,#64748b 50%,#c47b3e)','linear-gradient(145deg,#120f1f,#314f87 50%,#e06b36)','linear-gradient(145deg,#0b1426,#334c71 55%,#8e5b39)','linear-gradient(145deg,#183c36,#5b9b83 52%,#e7a64a)','linear-gradient(145deg,#11172d,#3559a4 48%,#9b5ce0)','linear-gradient(145deg,#19191d,#4d3434 50%,#d07b43)','linear-gradient(145deg,#101c32,#275a86 50%,#d88b48)','linear-gradient(145deg,#061d38,#177bc0 48%,#ff9a3c)','linear-gradient(145deg,#12151f,#45526c 55%,#b54b42)','linear-gradient(145deg,#193529,#5c8b5e 55%,#d6a04e)'
];
const view=document.querySelector('#view'),detail=document.querySelector('#detail'),search=document.querySelector('#search'),results=document.querySelector('#search-results'),input=document.querySelector('#search-input');
const historyKey='oritv-history',favKey='oritv-favorites';let currentZone='nav',pos=0,navPos=0;
const getHistory=()=>JSON.parse(localStorage.getItem(historyKey)||'[]');
const getFavs=()=>JSON.parse(localStorage.getItem(favKey)||'[]');
const saveHistory=i=>{let h=getHistory().filter(x=>x!==i);h.unshift(i);localStorage.setItem(historyKey,JSON.stringify(h.slice(0,30)))};
const toggleFav=i=>{let f=getFavs();f=f.includes(i)?f.filter(x=>x!==i):[i,...f];localStorage.setItem(favKey,JSON.stringify(f));return f.includes(i)};
const poster=i=>posters[i%posters.length];
const card=(x,i)=>`<button class="card focusable" data-id="${i}"><span class="poster" style="background:${poster(i)}"></span><span class="card-rating">${x[3]}</span><span class="card-info"><span class="card-title">${x[0]}</span><span class="card-sub">${x[1]} · ${x[2]}</span></span></button>`;
const row=(t,a)=>a.length?`<section class="row"><h2 class="row-title">${t}</h2><div class="cards">${a.map(i=>card(data[i],i)).join('')}</div></section>`:'';
function nav(a){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.action===a))}
function visibleFocus(){return [...document.querySelectorAll('.nav-item,.view .focusable')].filter(x=>{const r=x.getBoundingClientRect();return r.width>0&&r.height>0})}
function setFocus(el){if(!el)return;document.querySelectorAll('.focused').forEach(x=>x.classList.remove('focused'));el.classList.add('focused');el.scrollIntoView({block:'nearest',inline:'nearest'})}
function focusNav(n){let a=[...document.querySelectorAll('.nav-item')];if(!a.length)return;currentZone='nav';navPos=Math.max(0,Math.min(n,a.length-1));setFocus(a[navPos])}
function focusContent(n){let a=[...view.querySelectorAll('.focusable')];if(!a.length)return;currentZone='content';pos=Math.max(0,Math.min(n,a.length-1));setFocus(a[pos])}
function move(dir){let all=visibleFocus(),cur=document.querySelector('.focused');if(!cur)return;let r=cur.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let candidates=all.filter(x=>x!==cur).map(x=>{let q=x.getBoundingClientRect(),x2=q.left+q.width/2,y2=q.top+q.height/2,dx=x2-cx,dy=y2-cy;let primary=dir==='left'?-dx:dir==='right'?dx:dir==='up'?-dy:dy;let cross=dir==='left'||dir==='right'?Math.abs(dy):Math.abs(dx);return {x,primary,cross,dist:Math.hypot(dx,dy)}}).filter(o=>o.primary>4).sort((a,b)=>(a.cross-b.cross)*2+(a.dist-b.dist));if(candidates[0]){setFocus(candidates[0].x);if(candidates[0].x.classList.contains('nav-item')){currentZone='nav';navPos=[...document.querySelectorAll('.nav-item')].indexOf(candidates[0].x)}else{currentZone='content';pos=[...view.querySelectorAll('.focusable')].indexOf(candidates[0].x)}}}
function bind(){view.querySelectorAll('.focusable').forEach(e=>e.onclick=()=>e.dataset.id!==undefined?open(+e.dataset.id):act(e.dataset.action));focusContent(0)}
function home(){let h=getHistory();view.innerHTML=`<section class="hero" style="background:${poster(0)}"><div class="hero-inner"><div class="eyebrow">ORITV · ПРЕМЬЕРА</div><h1>${data[0][0]}</h1><div class="tagline">Когда путь домой становится последней надеждой.</div><div class="meta">${data[0][1]} · ${data[0][2]} · ${data[0][3]}</div><div class="tags"><span class="tag">4K</span><span class="tag">HDR</span><span class="tag">Оригинал</span></div><div class="actions"><button class="action primary focusable" data-id="0">▶ Смотреть</button><button class="action focusable" data-id="0">Подробнее</button></div></div></section><div class="rows">${row('Продолжить просмотр',h.slice(0,6))}${row('Популярное сейчас',[3,4,6,0,7,8,9])}${row('Новые фильмы',[0,1,2,3,7,9])}${row('Сериалы',[4,8,10])}${row('Мультфильмы',[5,11])}${row('Аниме',[6])}</div>`;nav('home');bind()}
function list(type){let a=[];if(type==='history')a=getHistory();else if(type==='favorite')a=getFavs();else a=data.map((x,i)=>i).filter(i=>type==='all'?data[i][4]==='фильм':data[i][4]===type);let title=type==='all'?'Фильмы':type==='history'?'История':type==='favorite'?'Избранное':type==='мультфильм'?'Мультфильмы':type==='аниме'?'Аниме':'Сериалы';view.innerHTML=`<h1 class="page-title">${title}</h1><div class="grid">${a.map(i=>card(data[i],i)).join('')||'<p class="empty">Здесь пока ничего нет.</p>'}</div>`;nav(type==='all'?'movies':type==='history'?'history':type==='favorite'?'favorites':type==='мультфильм'?'cartoons':type==='аниме'?'anime':'series');bind()}
function settings(){view.innerHTML='<section class="settings"><h1>Настройки</h1><div class="setting-grid"><button class="setting focusable">Источники<br><small>Ваши источники подключаются отдельно.</small></button><button class="setting focusable">Плеер<br><small>Качество, субтитры и запуск.</small></button><button class="setting focusable">Интерфейс<br><small>Синий + оранжевый стиль OriTV.</small></button><button class="setting focusable">Пульт<br><small>Стрелки, OK, Back и Magic Remote.</small></button></div></section>';nav('settings');bind()}
function open(i){let x=data[i],fav=getFavs().includes(i);saveHistory(i);detail.querySelector('.detail-backdrop').style.background=poster(i);document.querySelector('#detail-meta').innerHTML=`<div class="detail-info"><div class="eyebrow">${x[4].toUpperCase()} · ${x[1]}</div><h1>${x[0]}</h1><div class="tagline">${x[2]} · рейтинг ${x[3]}</div><div class="tags"><span class="tag">4K</span><span class="tag">HDR</span></div><p class="detail-copy">Здесь будет запуск вашего источника и плеера OriTV.</p><div class="actions"><button class="action primary focusable" data-action="close-detail">‹ Назад</button><button class="action focusable" data-action="toggle-fav">${fav?'♥ В избранном':'♡ В избранное'}</button></div></div>`;detail.classList.remove('hidden');detail.querySelector('[data-action="close-detail"]').onclick=closeDetail;detail.querySelector('[data-action="toggle-fav"]').onclick=()=>{let on=toggleFav(i);detail.querySelector('[data-action="toggle-fav"]').textContent=on?'♥ В избранном':'♡ В избранное'}}
function closeDetail(){detail.classList.add('hidden');focusContent(pos)}
function act(a){if(a==='home')home();else if(a==='movies')list('all');else if(a==='series')list('сериал');else if(a==='cartoons')list('мультфильм');else if(a==='anime')list('аниме');else if(a==='history')list('history');else if(a==='favorites')list('favorite');else if(a==='settings')settings();else if(a==='search'){search.classList.remove('hidden');results.innerHTML=data.map((x,i)=>card(x,i)).join('');results.querySelectorAll('.card').forEach(e=>e.onclick=()=>open(+e.dataset.id));input.focus()}}
input.oninput=e=>{let q=e.target.value.toLowerCase();results.innerHTML=data.filter(x=>(x[0]+' '+x[2]).toLowerCase().includes(q)).map((x)=>card(x,data.indexOf(x))).join('');results.querySelectorAll('.card').forEach(e=>e.onclick=()=>open(+e.dataset.id))};
document.addEventListener('keydown',e=>{if(!detail.classList.contains('hidden')){if(e.key==='Escape'||e.key==='Backspace'||e.keyCode===461)closeDetail();return}if(!search.classList.contains('hidden')){if(e.key==='Escape'||e.key==='Backspace'||e.keyCode===461){search.classList.add('hidden');home()}return}if(e.key==='ArrowLeft')move('left');else if(e.key==='ArrowRight')move('right');else if(e.key==='ArrowUp')move('up');else if(e.key==='ArrowDown')move('down');else if(e.key==='Enter'||e.keyCode===13)document.querySelector('.focused')?.click();else if(e.key==='Escape'||e.key==='Backspace'||e.keyCode===461)home()});
addEventListener('load',()=>{home();setTimeout(()=>focusNav(0),100)});
})();