(()=>{'use strict';
const TOKEN_KEY='oritv-tmdb-token',CACHE_KEY='oritv-tmdb-cache-v1',FAV_KEY='oritv-tmdb-favorites',HIST_KEY='oritv-tmdb-history';
const $=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const token=()=>localStorage.getItem(TOKEN_KEY)||'';const cache=()=>{try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'{}')}catch(_){return {}}};const saveCache=v=>{try{localStorage.setItem(CACHE_KEY,JSON.stringify(v))}catch(_){}};
const favs=()=>{try{return JSON.parse(localStorage.getItem(FAV_KEY)||'[]')}catch(_){return []}};const saveFavs=v=>localStorage.setItem(FAV_KEY,JSON.stringify(v));
const history=()=>{try{return JSON.parse(localStorage.getItem(HIST_KEY)||'[]')}catch(_){return []}};const saveHistory=v=>localStorage.setItem(HIST_KEY,JSON.stringify(v));
const img=(p,s='w500')=>p?'https://image.tmdb.org/t/p/'+s+p:'';const title=x=>x.title||x.name||'';const date=x=>x.release_date||x.first_air_date||'';const year=x=>(date(x)||'').slice(0,4)||'—';
const type=x=>x.media_type==='tv'||x.first_air_date?'сериал':'фильм';
async function api(path,params={}){const t=token();if(!t)throw Error('TMDB_TOKEN');const u=new URL('https://api.themoviedb.org/3'+path);Object.entries({...params,language:'ru-RU'}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{headers:{Authorization:'Bearer '+t,accept:'application/json'}});if(!r.ok)throw Error('TMDB_'+r.status);return r.json()}
async function cached(key,fn,ttl=900000){const c=cache(),hit=c[key];if(hit&&Date.now()-hit.time<ttl)return hit.data;const data=await fn();c[key]={time:Date.now(),data};saveCache(c);return data}
function card(x){const t=type(x),id=x.id;return `<button class="card focusable tmdb-card" data-tmdb-id="${id}" data-tmdb-type="${t}"><img class="poster-img" src="${img(x.poster_path,'w500')}" alt="${esc(title(x))}" onerror="this.style.display='none'"><span class="card-type">${t}</span><span class="card-rating">${Number(x.vote_average||0).toFixed(1)}</span><span class="card-info"><span class="card-title">${esc(title(x))}</span><span class="card-sub">${year(x)} · TMDB</span></span></button>`}
function row(name,items){return `<section class="row tmdb-row"><h2 class="row-title">${esc(name)}</h2><div class="cards">${items.filter(x=>x.poster_path).slice(0,12).map(card).join('')}</div></section>`}
function credit(){return `<div class="tmdb-credit"><strong>Данные и изображения: TMDB.</strong><br>This product uses the TMDB API but is not endorsed or certified by TMDB. <a href="https://www.themoviedb.org" target="_blank" rel="noopener">The Movie Database</a></div>`}
async function home(){const v=$('#view');if(!v)return;v.innerHTML='<div class="tmdb-loading">Загружаем каталог TMDB…</div>';try{const [trend,movies,tv]=await Promise.all([cached('trend-all-week',()=>api('/trending/all/week')),cached('popular-movies',()=>api('/movie/popular',{region:'RU'})),cached('popular-tv',()=>api('/tv/popular',{region:'RU'}))]);const hero=(trend.results||[]).find(x=>x.backdrop_path)||trend.results?.[0];v.innerHTML=`<div class="tmdb-wrap">${hero?`<section class="tmdb-hero"><img class="tmdb-hero-art" src="${img(hero.backdrop_path,'w1280')}" alt=""><div class="tmdb-hero-shade"></div><div class="tmdb-hero-inner"><div class="eyebrow">TMDB · ТРЕНДЫ</div><h1>${esc(title(hero))}</h1><div class="tagline">${esc(hero.overview||'Популярное сейчас на TMDB.')}</div><div class="meta">${year(hero)} · ${type(hero)} · рейтинг ${Number(hero.vote_average||0).toFixed(1)}</div><div class="tags"><span class="tag">TMDB</span><span class="tag">HD</span></div></div></section>`:''}${row('Популярное сейчас',trend.results||[])}${row('Новые фильмы',movies.results||[])}${row('Сериалы',tv.results||[])}${credit()}</div>`;bindCards();}catch(e){v.innerHTML='<div class="tmdb-wrap"><div class="tmdb-empty">TMDB не загрузился. Проверь API Read Access Token в настройках.</div></div>'}}
async function list(kind){const v=$('#view');v.innerHTML='<div class="tmdb-loading">Загружаем TMDB…</div>';try{let data,name;if(kind==='movies'){data=await cached('page-movies',()=>api('/movie/popular',{region:'RU'}));name='Фильмы'}else if(kind==='series'){data=await cached('page-tv',()=>api('/tv/popular',{region:'RU'}));name='Сериалы'}else if(kind==='cartoons'){data=await cached('page-cartoons',()=>api('/discover/movie',{with_genres:16,sort_by:'popularity.desc',region:'RU'}));name='Мультфильмы'}else if(kind==='anime'){data=await cached('page-anime',()=>api('/discover/tv',{with_genres:16,with_origin_country:'JP',sort_by:'popularity.desc'}));name='Аниме'}else if(kind==='favorites'){const ids=favs();const items=[];for(const f of ids.slice(0,30)){try{items.push(await api('/'+f.type+'/'+f.id))}catch(_){}}v.innerHTML=`<div class="tmdb-wrap"><h1 class="page-title">Избранное</h1>${items.length?row('',items):'<div class="tmdb-empty">В избранном пока ничего нет.</div>'}${credit()}</div>`;bindCards();return}else if(kind==='history'){const ids=history(),items=[];for(const f of ids.slice(0,30)){try{items.push(await api('/'+f.type+'/'+f.id))}catch(_){}}v.innerHTML=`<div class="tmdb-wrap"><h1 class="page-title">История</h1>${items.length?row('',items):'<div class="tmdb-empty">История пока пуста.</div>'}${credit()}</div>`;bindCards();return}v.innerHTML=`<div class="tmdb-wrap"><h1 class="page-title">${name}</h1>${row('',data.results||[])}${credit()}</div>`;bindCards()}catch(e){v.innerHTML='<div class="tmdb-wrap"><div class="tmdb-empty">Не удалось загрузить TMDB. Проверь токен и интернет.</div></div>'}}
function bindCards(){document.querySelectorAll('.tmdb-card').forEach(b=>{b.onclick=()=>openDetail(b.dataset.tmdbId,b.dataset.tmdbType==='сериал'?'tv':'movie')})}
async function openDetail(id,kind){const d=$('#detail');if(!d)return;window.__oriTmdbDetail=true;history.pushState({oritvTmdb:true},'',`#/tmdb/${kind}/${id}`);d.classList.remove('hidden');$('#detail-meta').innerHTML='<div class="detail-info"><div class="tmdb-loading">Загружаем карточку TMDB…</div></div>';try{const x=await api('/'+kind+'/'+id,{append_to_response:'credits,videos'});const fav=favs().some(f=>f.id==id&&f.type===kind);const key={id:Number(id),type:kind};saveHistory([key,...history().filter(f=>!(f.id==id&&f.type===kind))].slice(0,50));d.querySelector('.detail-backdrop').innerHTML=`<img class="tmdb-detail-art" src="${img(x.backdrop_path||x.poster_path,'original')}" alt=""><div class="tmdb-detail-shade"></div>`;const overview=x.overview||'Описание пока отсутствует.';$('#detail-meta').innerHTML=`<div class="detail-info"><div class="eyebrow">${kind==='tv'?'СЕРИАЛ':'ФИЛЬМ'} · ${year(x)} · TMDB</div><h1>${esc(title(x))}</h1><div class="tagline">${esc(x.tagline||overview.slice(0,170))}</div><div class="ratings"><span class="rating-main">★ ${Number(x.vote_average||0).toFixed(1)}</span><span>${year(x)}</span><span>TMDB</span></div><p class="detail-copy">${esc(overview)}</p><div class="actions"><button class="action primary focusable" data-tmdb-play>▶ Смотреть</button><button class="action focusable" data-tmdb-fav>${fav?'♥ В избранном':'♡ В избранное'}</button></div>${credit()}</div>`;const bs=[...d.querySelectorAll('.focusable')];bs[0]?.focus();bs.forEach(b=>{b.onclick=()=>{if(b.hasAttribute('data-tmdb-fav')){let f=favs();const ix=f.findIndex(z=>z.id==id&&z.type===kind);if(ix>=0){f.splice(ix,1);b.textContent='♡ В избранное'}else{f.unshift(key);b.textContent='♥ В избранном'}saveFavs(f)}else{const t=$('#toast');t.textContent='Плеер подключается к вашим источникам';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}}})}catch(_){$('#detail-meta').innerHTML='<div class="detail-info"><h1>TMDB</h1><p class="detail-copy">Не удалось получить данные.</p></div>'}}
function closeTmdbDetail(){if(!window.__oriTmdbDetail)return false;window.__oriTmdbDetail=false;$('#detail')?.classList.add('hidden');if(location.hash.startsWith('#/tmdb/'))history.back();return true}
function modal(){document.querySelector('.tmdb-modal')?.remove();const m=document.createElement('div');m.className='tmdb-modal';m.innerHTML=`<div class="tmdb-panel"><button class="tmdb-modal-close">×</button><h2>TMDB карточки</h2><p>Подключи свой TMDB API Read Access Token. Он сохранится только на этом телевизоре в localStorage и используется напрямую из браузера.</p><div class="tmdb-form"><input class="tmdb-token" type="password" placeholder="TMDB API Read Access Token" value="${esc(token())}"><button class="tmdb-save">Подключить</button></div><div class="tmdb-status">${token()?'Токен сохранён · TMDB включён':'TMDB пока не подключён'}</div><div class="tmdb-about">Нужен бесплатный ключ для некоммерческого использования с обязательной атрибуцией TMDB. <a href="https://developer.themoviedb.org/docs/getting-started" target="_blank" rel="noopener">Документация TMDB</a></div></div>`;document.body.appendChild(m);m.querySelector('.tmdb-modal-close').onclick=()=>m.remove();m.querySelector('.tmdb-save').onclick=async()=>{const t=m.querySelector('.tmdb-token').value.trim();if(!t)return;m.querySelector('.tmdb-status').textContent='Проверяем токен…';try{localStorage.setItem(TOKEN_KEY,t);await api('/configuration');m.remove();localStorage.removeItem(CACHE_KEY);location.hash='#/home';await home()}catch(_){localStorage.removeItem(TOKEN_KEY);m.querySelector('.tmdb-status').textContent='Токен не принят. Проверь его в TMDB.'}}}
function addSetting(){const grid=document.querySelector('.setting-grid');if(!grid||grid.querySelector('[data-tmdb-settings]'))return;const b=document.createElement('button');b.className='setting focusable tmdb-source-btn';b.setAttribute('data-tmdb-settings','1');b.innerHTML='<strong>TMDB карточки</strong><small>Постеры, рейтинги, описания и каталог TMDB.</small>';grid.appendChild(b)}
function route(){const h=location.hash||'#/home';if(!token())return;if(h==='#/home'){home();return}if(h==='#/movies'){list('movies');return}if(h==='#/series'){list('series');return}if(h==='#/cartoons'){list('cartoons');return}if(h==='#/anime'){list('anime');return}if(h==='#/favorites'){list('favorites');return}if(h==='#/history'){list('history');return}if(h==='#/settings'){addSetting()}}
let lastRoute='';function sync(){addSetting();if(!token())return;const h=location.hash||'#/home';if(h.startsWith('#/tmdb/'))return;if(h!==lastRoute||!document.querySelector('.tmdb-card')){lastRoute=h;route()}}
document.addEventListener('click',e=>{if(e.target.closest('[data-tmdb-settings]')){e.preventDefault();e.stopPropagation();modal();return}if(e.target.closest('.nav-item'))setTimeout(sync,120)},true);
document.addEventListener('keydown',e=>{if((e.keyCode===461||e.keyCode===27||e.keyCode===8)&&window.__oriTmdbDetail){e.preventDefault();e.stopImmediatePropagation();closeTmdbDetail()}},true);
window.addEventListener('popstate',e=>{if(window.__oriTmdbDetail){window.__oriTmdbDetail=false;$('#detail')?.classList.add('hidden');return}const h=location.hash||'#/home';if(h.startsWith('#/tmdb/')){e.stopImmediatePropagation();const p=h.split('/');openDetail(p[3],p[2]);return}setTimeout(sync,100)});
window.addEventListener('load',()=>{setTimeout(sync,250);setInterval(sync,900);const inp=$('#search-input');if(inp){inp.addEventListener('input',()=>{clearTimeout(window.__tmdbSearchTimer);window.__tmdbSearchTimer=setTimeout(async()=>{if(!token()||$('#search')?.classList.contains('hidden'))return;const q=inp.value.trim();if(!q){$('#search-results').innerHTML='';return}try{const d=await api('/search/multi',{query:q,include_adult:false});$('#search-results').innerHTML=(d.results||[]).filter(x=>x.media_type==='movie'||x.media_type==='tv').map(card).join('');bindCards()}catch(_){}},300)},true)}});
window.OriTVTMDB={token,home,openDetail};
})();
