(()=>{'use strict';
const KEY='oritv-settings-v19';
const defaults={interface_size:'Средний',theme:'Тёмная',background:true,background_type:'Динамический',animations:true,glass:true,card_quality:true,card_episodes:true,start_page:'Главная',source:'TMDB',protocol:true,request_caching:true,screensaver:true,screensaver_time:'10 минут',navigation_type:'Пульт / 5-way',keyboard_type:'Lampa',device_name:'OriTV TV',player:'HTML5',player_quality:'Авто',audio:'Авто',subtitles:true,subtitle_size:'Средний',autoplay:false,parser_url:'',torrserver_url:'',torrserver_auth:false,plugins:true,parental:false,parental_pin:'',language:'Русский'};
const cats=[['general','⚙','Основные'],['interface','◉','Интерфейс'],['player','▶','Плеер'],['sources','◎','Источники'],['parser','⌁','Парсер'],['torrserver','◈','TorrServer'],['plugins','✚','Плагины'],['parental','▣','Родительский контроль'],['more','⋮','Дополнительно']];
let state={...defaults};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){ };
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch(_){}};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function item(k,title,desc,type='toggle',opts=[]){let c='';if(type==='toggle')c=`<button class="v19-toggle ${state[k]?'on':''}" data-k="${k}" data-type="toggle" aria-label="${esc(title)}"></button>`;else if(type==='select')c=`<select class="v19-control" data-k="${k}">${opts.map(o=>`<option ${state[k]===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`;else if(type==='input')c=`<input class="v19-control" data-k="${k}" value="${esc(state[k]||'')}" placeholder="${esc(desc)}">`;else c=`<button class="v19-btn" data-k="${k}">${esc(opts[0]||'Открыть')}</button>`;return `<div class="v19-item"><div><strong>${esc(title)}</strong><small>${esc(desc)}</small></div>${c}</div>`}
function body(cat){const S={
 general:[item('start_page','Стартовая страница','Что открывать после запуска','select',['Главная','История','Фильмы','Сериалы']),item('source','Источник каталога','TMDB используется автоматически','select',['TMDB','TMDB + мои источники']),item('protocol','HTTPS запросы','Использовать защищённые запросы'),item('request_caching','Кэш запросов','Сохранять ответы локально'),item('language','Язык','Язык интерфейса','select',['Русский','English']),item('device_name','Имя устройства','Имя OriTV в сети','input')],
 interface:[item('theme','Тема','Основная тема','select',['Тёмная','Системная']),item('interface_size','Размер интерфейса','Размер элементов на TV','select',['Маленький','Средний','Большой']),item('background','Фон','Показывать фон карточек'),item('background_type','Тип фона','Вариант динамического фона','select',['Динамический','Постер','Статический']),item('animations','Анимации','Плавные переходы интерфейса'),item('glass','Glass стиль','Полупрозрачные панели'),item('card_quality','Метки качества','Показывать 4K/HDR на карточках'),item('card_episodes','Количество серий','Показывать серии на карточках')],
 player:[item('player','Видео движок','Основной HTML5-плеер','select',['HTML5','WebOS Media']),item('player_quality','Качество','Предпочтительное качество','select',['Авто','4K','1080p','720p']),item('audio','Аудио','Дорожка по умолчанию','select',['Авто','Русская','Оригинал']),item('subtitles','Субтитры','Включать субтитры автоматически'),item('subtitle_size','Размер субтитров','Размер текста','select',['Маленький','Средний','Большой']),item('autoplay','Автозапуск','Продолжать воспроизведение автоматически')],
 sources:[`<div class="v19-note">TMDB работает автоматически. В этом разделе оставляем место для твоих собственных каталогов и Lampa-compatible источников.</div>`,item('source_add','Добавить источник','URL JSON/API каталога','button',['Открыть источники'])],
 parser:[item('parser_url','URL парсера','Jackett / Prowlarr или совместимый API','input'),`<div class="v19-note">Настройка сохранена локально на телевизоре. Подключение конкретного парсера добавим через адаптер.</div>`],
 torrserver:[item('torrserver_url','TorrServer URL','Адрес TorrServer','input'),item('torrserver_auth','Авторизация','Использовать логин и пароль'),`<div class="v19-note">Если TorrServer не используется, оставь эти параметры выключенными.</div>`],
 plugins:[item('plugins','Плагины','Разрешить загрузку расширений'),`<div class="v19-note">Плагины будут подключаться только из разрешённых URL. Архитектуру оставляем совместимой с Lampa-подходом.</div>`],
 parental:[item('parental','Родительский контроль','Защищать выбранные разделы'),item('parental_pin','PIN','PIN-код родительского контроля','input'),`<div class="v19-note">После включения сюда добавим защиту Настроек, источников и других разделов.</div>`],
 more:[item('screensaver','Заставка','Запускать заставку после простоя'),item('screensaver_time','Время заставки','Период бездействия','select',['5 минут','10 минут','20 минут','30 минут']),item('navigation_type','Навигация','Режим управления','select',['Пульт / 5-way','Magic Remote','Клавиатура']),item('keyboard_type','Клавиатура','Виртуальная клавиатура','select',['Lampa','Простая']),`<div class="v19-note">Настройки сохраняются в localStorage, поэтому после перезапуска TV они остаются на месте.</div>`]};return S[cat]||S.general}
function open(cat='general'){if(document.querySelector('.v19-settings'))return;const o=document.createElement('div');o.className='v19-settings';o.innerHTML=`<div class="v19-panel"><aside class="v19-side"><div class="v19-head"><strong>OriTV</strong><small>Настройки</small></div>${cats.map(x=>`<button class="v19-cat ${x[0]===cat?'active':''}" data-cat="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</aside><main class="v19-main"><div class="v19-top"><div><h1 id="v19-title"></h1><p id="v19-desc">Настройки OriTV на базе подхода Lampa</p></div><button class="v19-close">×</button></div><div class="v19-section" id="v19-body"></div></main></div>`;document.body.appendChild(o);const title=o.querySelector('#v19-title');const render=c=>{const x=cats.find(a=>a[0]===c)||cats[0];title.textContent=x[2];o.querySelectorAll('.v19-cat').forEach(b=>b.classList.toggle('active',b.dataset.cat===c));o.querySelector('#v19-body').innerHTML=body(c);bindBody()};const bindBody=()=>{o.querySelectorAll('[data-type="toggle"]').forEach(b=>b.onclick=()=>{const k=b.dataset.k;state[k]=!state[k];b.classList.toggle('on',state[k]);save()});o.querySelectorAll('select[data-k]').forEach(s=>s.onchange=()=>{state[s.dataset.k]=s.value;save()});o.querySelectorAll('input[data-k]').forEach(i=>i.onchange=()=>{state[i.dataset.k]=i.value;save()});const add=o.querySelector('[data-k="source_add"]');if(add)add.onclick=()=>{o.remove();window.OriTVV16?.openSources?.()}};o.querySelectorAll('.v19-cat').forEach(b=>b.onclick=()=>render(b.dataset.cat));o.querySelector('.v19-close').onclick=()=>o.remove();render(cat)}
function boot(){document.addEventListener('click',e=>{const a=e.target.closest('[data-action="settings"]');if(a){e.preventDefault();e.stopImmediatePropagation();open('general');return}const s=e.target.closest('.setting');if(s){e.preventDefault();e.stopImmediatePropagation();open('general')}},true);window.OriTVV19={open,settings:state}}
window.addEventListener('load',boot);
})();